import type { Prediction } from "@/lib/predictions";
import SNAPSHOT from "./data-snapshot.json";

/**
 * Real-data feed (build-time snapshot).
 *
 * lib/data-snapshot.json is generated by scripts/bundle-data.mjs from the
 * latest backend/app/daily/*.json files (forebet + model fusion). It's
 * imported statically so Vercel's serverless build always carries it.
 * No API key needed.
 */

const dec = (american?: number | null): string => {
  if (american == null || !Number.isFinite(american)) return "—";
  try {
    const d = american > 0 ? 1 + american / 100 : 1 + 100 / Math.abs(american);
    return d.toFixed(2);
  } catch {
    return "—";
  }
};

// ---------- FOOTBALL (full-crack: forebet + model fusion, ~95 games/day) ----
function football(): Prediction[] {
  const rows = SNAPSHOT.football as any[];
  if (!Array.isArray(rows)) return [];
  const out: Prediction[] = [];
  rows.forEach((r: any, i: number) => {
    if (!r || !r.home || !r.away) return;
    const final = r.final || r.fb_pick || "";
    if (!final) return;
    const m = r.model || {};
    const bank = m.bank || "";
    const confidence: Prediction["confidence"] =
      bank === "BANKER" ? "High" : bank === "ODD" || r.src === "FOREBET" ? "Balanced" : "Value";
    let odds = "—";
    const mktDecArr = Array.isArray(r.mkt_dec) ? r.mkt_dec : null;
    const kO = final === "1" ? 0 : final === "2" ? 2 : 1;
    if (mktDecArr && typeof mktDecArr[kO] === "number" && (mktDecArr[kO] as number) > 1) {
      odds = (mktDecArr[kO] as number).toFixed(2);
    } else if (typeof r.mkt_dec === "number") {
      odds = Number(r.mkt_dec).toFixed(2);
    } else if (Array.isArray(r.fb_pct) && r.fb_pct.length === 3) {
      const p = final === "1" ? r.fb_pct[0] : final === "2" ? r.fb_pct[2] : r.fb_pct[1];
      if (p > 0) odds = (100 / p).toFixed(2);
    }
    const bits: string[] = [];
    const hasFb =
      Array.isArray(r.fb_pct) && r.fb_pct.length === 3 && r.fb_pct.some((x: number) => x > 0);
    if (hasFb) {
      bits.push(`Forebet ${r.fb_pct[0]}% / ${r.fb_pct[1]}% / ${r.fb_pct[2]}% (1/X/2).`);
    }
    if (r.fb_pick) bits.push(`Forebet pick: ${r.fb_pick}.`);
    if (r.fb_score) bits.push(`Predicted score ${r.fb_score}.`);
    if (m.pick) bits.push(`Model: ${m.p ? `${m.p[0]}% / ${m.p[1]}% / ${m.p[2]}%` : ""} → ${m.pick}.`);
    if (r.ou) bits.push(`Total: ${r.ou}.`);
    if (r.note) bits.push(r.note);
    out.push({
      id: `fb-${i}`,
      sport: "football",
      league: r.lg || "Football",
      home: r.home,
      away: r.away,
      kickoff: `Today · ${r.t || ""} WAT`,
      market: r.ou ? "Over / Under" : "1X2 (match winner)",
      tip: String(final).replace(/^1$/, "Home (1)").replace(/^2$/, "Away (2)").replace(/^X$/, "Draw (X)"),
      confidence,
      odds,
      banker: hasFb && Math.max(r.fb_pct[0], r.fb_pct[1], r.fb_pct[2]) >= 70,
      analysis: bits.join(" "),
    });
  });
  return out;
}

// ---------- BASKETBALL (forebet picks + deep-crack fusion) ------------------
function basketball(): Prediction[] {
  const d = SNAPSHOT.basketball as any;
  if (!d) return [];
  const out: Prediction[] = [];
  const seen = new Set<string>();
  (d.games || []).forEach((g: any, i: number) => {
    if (!g || !g.home || !g.away) return;
    const key = `${g.home}|${g.away}`;
    seen.add(key);
    out.push({
      id: `bb-${i}`,
      sport: "basketball",
      league: g.league || "Basketball",
      home: g.home,
      away: g.away,
      kickoff: `Today · ${g.t || ""} WAT`,
      market: "Moneyline",
      tip: g.pick || g.fb_pick || "",
      confidence:
        g.conf && /HIGH/.test(g.conf) ? "High" : g.conf && /SPLIT|LOW/.test(g.conf) ? "Value" : "Balanced",
      banker: !!g.conf && /HIGH/.test(g.conf) && !/SPLIT/.test(g.conf),
      odds: g.fb_coef ? dec(Number(String(g.fb_coef).split(/[\s/]+/).find((s) => /^[+-]?\d+$/.test(s)))) : "—",
      analysis: [
        g.fb_prob ? `Forebet ${g.fb_prob[0]}% / ${g.fb_prob[1]}%.` : "Not covered by Forebet.",
        g.fb_score ? `Forebet score ${g.fb_score}.` : "",
        g.why || "",
      ]
        .filter(Boolean)
        .join(" "),
    });
  });
  // remaining forebet rows (league games without a deep-crack)
  (d.forebet_today_all || []).forEach((g: any, i: number) => {
    if (!g || !g.match) return;
    const [home, away] = String(g.match).split(/\sv\s/i);
    if (!home || !away) return;
    if (seen.has(`${home}|${away}`)) return;
    const prob = String(g.prob || "").split("/");
    out.push({
      id: `bbf-${i}`,
      sport: "basketball",
      league: g.league || "Basketball",
      home,
      away,
      kickoff: `Today · ${g.t || ""} WAT`,
      market: "Moneyline",
      tip: g.pred === "1" ? `Home (${home})` : `Away (${away})`,
      confidence: prob.length === 2 && Number(prob[0] === "53" ? prob[0] : prob[0]) >= 60 ? "Balanced" : "Balanced",
      odds: g.coef ? dec(Number(String(g.coef).split(/[\s/]+/).find((s) => /^[+-]?\d+$/.test(s)))) : "—",
      analysis: [
        `Forebet ${g.prob || ""}%.`,
        g.score ? `Forebet score ${g.score}.` : "",
        g.status ? `Status: ${g.status}.` : "",
      ]
        .filter(Boolean)
        .join(" "),
    });
  });
  return out;
}

// ---------- TENNIS (forebet picks + set scores) ------------------------------
function tennis(): Prediction[] {
  const d = SNAPSHOT.tennis as any;
  if (!d) return [];
  const out: Prediction[] = [];
  (d.games || []).forEach((g: any, i: number) => {
    if (!g || !g.p1 || !g.p2) return;
    const coefStr = String(g.coef || "");
    const am = coefStr.match(/(-?\d{3,4})/);
    out.push({
      id: `tn-${i}`,
      sport: "tennis",
      league: g.tourn || "Tennis",
      home: g.p1,
      away: g.p2,
      kickoff: `Today · ${g.t || ""} WAT`,
      market: "Match winner",
      tip: g.pred || "",
      confidence: g.note && /BANKER/i.test(g.note) ? "High" : g.note && /SPLIT/i.test(g.note) ? "Value" : "Balanced",
      banker: !!g.note && /BANKER/i.test(g.note),
      odds: am ? dec(Number(am[1])) : "—",
      analysis: [
        `Forebet ${g.prob || ""} (player 1 / player 2).`,
        g.sets ? `Predicted sets ${g.sets}.` : "",
        g.note ? g.note + "." : "",
      ]
        .filter(Boolean)
        .join(" "),
    });
  });
  return out;
}

/** All local predictions across the three sports (empty if no daily data yet). */
export function loadLocalPredictions(): Prediction[] {
  return [...football(), ...basketball(), ...tennis()];
}
